### ISSUE TITLE
Dynamic code generation is not supported on this platform

### ISSUE THREAD

**Issue by 3400442579** [Onebeld/PleasantUI#2]
PleasantUI.Example    PublishTrimmed = true

![image](https://github.com/Onebeld/PleasantUI/assets/34226979/94c2cdf4-7f66-4b9f-87dd-aafbb6d8eaea)

**Comment by Onebeld** [comment]
Hi! I apologize for the late reply.
For some reason unknown to me, publishing via IDE is not possible if NativeAOT is activated in the project. Please use this command in the project folder:

```shell
dotnet publish -r win-x64 -c Release
```

**Comment by Onebeld** [comment]
Since there hasn't been a response, I'm closing this issue as resolved. If anything comes up, feel free to reach out and I'll reopen it.
